remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
docs_dir: docs
baseurl: "/personal_blog2"
back_to_top: true
back_to_top_text: "Back to top"

