remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
docs_dir: docs
baseurl: "/personal_blog2"
show_toc: true

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6   # include all heading levels from # to ######
extra_css:
  - assets/css/custom.css
extra_js:
  - assets/js/back-to-top.js
  - assets/js/dark-mode-toggle.js


